#!/usr/bin/env node
/* Self-host the web fonts (Sora, DM Sans, Caveat) so first paint never waits on
   fonts.googleapis.com / fonts.gstatic.com — a third-party round trip that is slow
   on some networks and unreachable on others — and so the PWA precache can serve
   them offline.

   Run only when the family list or weights change:   node scripts/build-fonts.mjs
   Output (committed): public/fonts/*.woff2 + public/fonts/fonts.css

   All three families are variable fonts: every weight of a family/style/subset is
   the same file, so each is emitted as ONE @font-face with a weight range. Only the
   latin + latin-ext subsets are kept (en/es/fr and friends); CJK and Cyrillic text
   falls through to the system font stack, same as before. Keep the weights in sync
   with what src/core/base.css and public/landing.css actually use. */

import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const OUT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..', 'public', 'fonts');
const SUBSETS = new Set(['latin', 'latin-ext']);
const FAMILIES =
  'family=Sora:wght@400;500;600;700;800' +
  '&family=DM+Sans:ital,wght@0,400;0,500;0,600;0,700;1,400' +
  '&family=Caveat:wght@500;600;700';
// A modern UA makes Google serve woff2 + unicode-range subsets.
const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36';

const css = await (await fetch(`https://fonts.googleapis.com/css2?${FAMILIES}&display=swap`, { headers: { 'user-agent': UA } })).text();

// One entry per (family, style, subset); weights merged into a min–max range.
const faces = new Map();
for (const m of css.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*@font-face\s*{([^}]*)}/g)) {
  const [, subset, body] = m;
  if (!SUBSETS.has(subset)) continue;
  const get = (prop) => body.match(new RegExp(`${prop}:\\s*([^;]+);`))?.[1].trim();
  const family = get('font-family').replace(/['"]/g, '');
  const style = get('font-style');
  const weight = Number(get('font-weight'));
  const url = body.match(/url\(([^)]+)\)/)[1];
  const range = get('unicode-range');
  const key = `${family}|${style}|${subset}`;
  const f = faces.get(key) ?? { family, style, subset, url, range, min: weight, max: weight };
  f.min = Math.min(f.min, weight);
  f.max = Math.max(f.max, weight);
  faces.set(key, f);
}

await mkdir(OUT, { recursive: true });
let outCss = '/* Generated by scripts/build-fonts.mjs — do not edit by hand. */\n';
for (const f of faces.values()) {
  const file = `${f.family.toLowerCase().replace(/\s+/g, '-')}-${f.style}-${f.subset}.woff2`;
  const buf = Buffer.from(await (await fetch(f.url)).arrayBuffer());
  await writeFile(path.join(OUT, file), buf);
  outCss += `@font-face {
  font-family: '${f.family}';
  font-style: ${f.style};
  font-weight: ${f.min === f.max ? f.min : `${f.min} ${f.max}`};
  font-display: swap;
  src: url(/fonts/${file}) format('woff2');
  unicode-range: ${f.range};
}
`;
  console.log(`${file}  ${(buf.length / 1024).toFixed(1)}KB  wght ${f.min}-${f.max}`);
}
await writeFile(path.join(OUT, 'fonts.css'), outCss);
console.log(`\n${faces.size} faces → public/fonts/fonts.css`);
